import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// DailyDevotionalBible — generated by AppFactoryKit appgen from niche "faith-devotional".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum DailyDevotionalBibleFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "DailyDevotionalBible",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "book.fill",
                          title: "DailyDevotionalBible",
                          message: "Daily verses, devotionals, prayer log."),
                    .init(systemImage: "hands.sparkles.fill",
                          title: "Go Pro",
                          message: "Full plans, audio, journaling, widgets, no ads.")
                ],
                presentsPaywallOnFinish: true,
                accent: .orange
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock DailyDevotionalBible Pro",
                subheadline: "Full plans, audio, journaling, widgets, no ads.",
                benefits: [
                    .init(systemImage: "infinity", title: "Full plans"),
                    .init(systemImage: "bolt.fill", title: "Audio"),
                    .init(systemImage: "nosign", title: "Journaling"),
                    .init(systemImage: "square.and.arrow.up", title: "Widgets"),
                    .init(systemImage: "star.fill", title: "No ads")
                ],
                productIDs: ["faith-devotional_yearly", "faith-devotional_weekly"],
                highlightedProductID: "faith-devotional_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .orange, heroSystemImage: "book.fill")
            )
        )
        return AppFactory(config)
    }
}

@main
struct DailyDevotionalBibleApp: App {
    @StateObject private var factory = DailyDevotionalBibleFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.orange)
        }
    }
}
